assets/urls.py
from django.urls import path

from . import views

app_name = 'assets'
urlpatterns = [
    path('', views.vehicle_list, name='vehicle_list'),
    path('<int:vehicle_id>/', views.vehicle_detail, name='vehicle_detail'),
    path('consumbles/', views.consumbles, name='consumbles'),
]

blog/urls.py
from django.urls import path

from.models import Post

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('post/<str:slug>/', views.PostsByCategory.as_view(), name='post'),
    path('category/<str:slug>/', views.get_category, name='category'),
]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('assets/', include('assets.urls')),
    path('fasteners/', include('fasteners.urls')),
    path('blog/', include('blog.urls')),
    #ckeditor
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assets/models.py
from enum import unique
from django.db import models


class Vehicle(models.Model):
    """
    VIN - according to ISO 3779Vehicle
    """
    vin = models.CharField ("Vehicle identification number (VIN)", max_length=17, unique=True)
    assembly_date = models.DateField(auto_now=False, auto_now_add=False)
    entry_into_service = models.DateField(auto_now=False, auto_now_add=False)
    image = models.ImageField(upload_to='images/', null=True, blank=True)
   

    def __str__(self):
        return self.vin

    def wmi(self):
        """
        WMI - Manufacturer Identifier

        Managed by SAE
        """
        return self.vin[0:3]

    def vds(self):
        """
        VDS - Vehicle Attributes

        Managed by manufacturer        
        """
        return self.vin[3:8]

    def wheel_configuration(self):
        """
        VDS - Vehicle Attributes

        Managed by manufacturer        
        """
        return self.vin[4:7]

    def check_digit(self):
        """
        Check Digit

        Calculated value        
        """
        return self.vin[8]

    def model_year(self):
        """
        Model Year

        Managed by manufacturer        
        """
        return self.vin[9]

    def model_year(self):
        """
        Plant Code

        Managed by manufacturer        
        """
        return self.vin[10]



class General(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    assembly_level = models.CharField(max_length=24, default='Комплетно изграден')
    production_class = models.CharField(max_length=24, default='Камион')
    development_level = models.CharField(max_length=2, default='5')
    front_wheel_drive = models.CharField(max_length=6, default='Нема')
    axle_distance = models.CharField(max_length=14, default='3700mm')
    chassis_width = models.CharField(max_length=18, default='2550mm')
    chassis_adaptation = models.CharField(max_length=64, default='A, има водечка спојка која овозможува оштро свртување')
    # truck_model = models.CharField(max_length=2, default='R')
    transport_type = models.CharField(max_length=2, default='L')
    duty_class = models.CharField(max_length=2, default='M')
    chassis_height = models.CharField(max_length=24, default='N, Нормална')
    plate_language = models.CharField(max_length=12, default='English')
    axle_weight_front_technical = models.CharField(max_length=12, default='7500kg')
    axle_load_rear_technical = models.CharField(max_length=12, default='115000kg')
    total_weight = models.CharField(max_length=12, default='19000kg')
    preparation_for_toll_collect = models.CharField(max_length=6, default='Има')

    def __str__(self):
        return self.vehicle.vin

    def wheel_configuration(self):
        return self.vehicle.vin[4:7]
    
    def truck_model(self):
        return self.vehicle.vin[3]

    class Meta:
        verbose_name_plural = "General"

   

    

class LicencePlate(models.Model):
    '''Licence Plate'''
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    code = models.CharField(max_length=8, unique=True)
    is_valid = models.BooleanField()
    validity = models.DateField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return self.vehicle.vin


class EngineInfo(models.Model):
    '''Engine'''
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    stroke_volume = models.CharField(max_length=2, default="13")
    power_code = models.CharField(max_length=5, default="410hp")
    type_vehicle = models.CharField(max_length=14, default="DC13 115/410hp")
    type_symbol = models.CharField(max_length=12, default="DC13 115 L01")
    serial_no = models.CharField(max_length=7)
    cylinder_block_generation = models.CharField(max_length=1, default="2")
    speed_limit_with_low_oil_presure = models.CharField(max_length=14, default='Without')
    egr_system = models.CharField(max_length=14, default='Without')
    egr_cooling = models.CharField(max_length=14, default='Not valid')
    emmission_level = models.CharField(max_length=14, default='Euro 6')
    management_system = models.CharField(max_length=2, default='S8')
    nox_control = models.CharField(max_length=14, default='With')
    torque_reduction_nox_control = models.CharField(max_length=14, default='With')
    power_take_of_ED = models.CharField(max_length=24, default='Prepared')
    power_take_of_ED_electical_preparation = models.CharField(max_length=24, default='Without')
    power_take_of_ED_control = models.CharField(max_length=14, default='Without')
    turbocharger_duty_class = models.CharField(max_length=14, default='Специјална')
    precleaner_air_intake = models.CharField(max_length=14, default='Without')
    air_intake = models.CharField(max_length=18, default='Front, normal')
    air_cleaner_engine_fire_resistant = models.CharField(max_length=14, default='Without')
    air_cleaner_safety_filter = models.CharField(max_length=14, default='Without')
    air_cleaner_engine_paper_area = models.CharField(max_length=14, default='13m²')
    air_intake_throttle_engine = models.CharField(max_length=14, default='With')
    air_intake_throttle_control = models.CharField(max_length=14, default='Electronic')
    air_filter_clogged_indicator = models.CharField(max_length=14, default='Electronic')
    noise_dampering = models.CharField(max_length=64, default='80 dBA acc to 70/157/EEC')
    noise_encapsulation_engine = models.CharField(max_length=18, default='With absorbents')
    crankcase_ventilation_type = models.CharField(max_length=14, default='Open')
    crankcase_ventilation_antitreeze = models.CharField(max_length=14, default='Without')
    oil_level_sensor_engine = models.CharField(max_length=14, default='Without')
    oil_level_sensor_monitoring = models.CharField(max_length=14, default='Without')
    oil_sump_material = models.CharField(max_length=14, default='Пластика')

    def __str__(self):
        return self.vehicle.vin

class FrontAxle(models.Model):
    '''Front Axle'''
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    type = models.CharField(max_length=12, default="AM740")

    def __str__(self):
        return self.vehicle.vin   

class RearAxle(models.Model):
    '''Rear Axle'''
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    type = models.CharField(max_length=12, default="ADA1100")
    oil_filter = models.CharField(max_length=12, default="Има")
    gear_first = models.CharField(max_length=12, default="R780")
    serial_no = models.CharField(max_length=12, default="2418002")
    gear_ratio = models.CharField(max_length=12, default="3.08")
    diferential_block = models.CharField(max_length=12, default="Има")
    hub_reduction = models.CharField(max_length=12, default="Нема")
    tag_axle_preparation = models.CharField(max_length=12, default="Нема")

    def __str__(self):
        return self.vehicle.vin   


class EngineControl(models.Model):
    '''Engine'''
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    speed_limiter = models.CharField(max_length=12, default="Има")
    speed_limitаtion = models.CharField(max_length=12, default="85km/h")
    speed_limit_second = models.CharField(max_length=12, default="Нема")
    speed_limit_third = models.CharField(max_length=12, default="Нема")

    def __str__(self):
        return self.vehicle.vin

class ComplementaryEquipment(models.Model):
    '''Engine'''
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    fifth_wheel = models.CharField(max_length=24, default="JOST JSK37C-Z 150")
    fifth_wheel_position = models.CharField(max_length=12, default="660")
    fifth_wheel_category = models.CharField(max_length=32, default="Fixed, plate-mounted")
    fifth_wheel_mounting_plate = models.CharField(max_length=24, default="40mm Dmax:152kN")
    catwalk = models.CharField(max_length=24, default="Единечна")
    bracket_front_mounted_equipment = models.CharField(max_length=24, default="Нема")
    acl_aut_chassis_lubrication = models.CharField('ACL, automatic chassis lubrication', max_length=24, default="Нема")
    dimension_ja_bep_lo2o = models.CharField('Dimesion JA/BEP L020', max_length=24, default="775")
    trailer_electric_connector = models.CharField(max_length=24, default="1x15 pole")
    trailer_connector_type = models.CharField(max_length=24, default="High")
    side_skirts = models.CharField(max_length=36, default="Without")
    resque_equip_except_fire_ex = models.CharField(max_length=24, default="With")
    hose_tyre_inflation = models.CharField(max_length=24, default="20")
    spare_wheel_carrier = models.CharField(max_length=24, default="Without")
    fire_extinguisher = models.CharField(max_length=24, default="1 x 2kg")

    def __str__(self):
        return self.vehicle.vin   

assets/views.py
from django.shortcuts import get_object_or_404, render

from .models import Vehicle


def vehicle_list(request):
    vehicle_list = Vehicle.objects.order_by('-assembly_date')
    total = Vehicle.objects.count()
    context = {
        'vehicle_list': vehicle_list,
        'total': total
    }
    return render(request, 'assets/vehicle_list.html', context)

def vehicle_detail(request, vehicle_id):
    vehicle = get_object_or_404(Vehicle, pk=vehicle_id)
    return render(request, 'assets/vehicle_detail.html', {'vehicle': vehicle})

def consumbles(request):
    vehicle_list = Vehicle.objects.order_by('-assembly_date')
    total = Vehicle.objects.count()
    context = {
        'vehicle_list': vehicle_list,
        'total': total
    }
    return render(request, 'assets/vehicle_list.html', context)

templates/assets/comsumbles.html
a{% extends 'base.html' %}
{% load static %}

{% block navar %}

<li class="nav-item">
    <span class="h6 text-secondary ps-4 ps-lg-6 mb-3 d-block text-uppercase">Getting started</span>
</li>

<li class="nav-item dropdown">
    <a class="nav-link" href="#customization" data-bs-toggle="collapse" role="button" aria-expanded="false"
        aria-controls="customization">
        <svg viewBox="0 0 24 24" class="nav-link-icon" height="18" width="18" xmlns="http://www.w3.org/2000/svg">
            <path d="M3.753,13.944v8.25h6v-6a1.5,1.5,0,0,1,1.5-1.5h1.5a1.5,1.5,0,0,1,1.5,1.5v6h6v-8.25" fill="none"
                stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></path>
            <path d="M.753,12.444,10.942,2.255a1.5,1.5,0,0,1,2.122,0L23.253,12.444" fill="none" stroke="currentColor"
                stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></path>
        </svg>
        <span>Assets</span>
    </a>
    <div class="collapse show" id="customization">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a href="{% url 'maint:index' %}" class="nav-link">Fleet</a>
            </li>
            <li class="nav-item">
                <a href="../docs/sass.html" class="nav-link">Equipment</a>
            </li>
            <li class="nav-item">
                <a href="../docs/javascript.html" class="nav-link">Tools</a>
            </li>
            <li class="nav-item">
                <a href="../docs/handlebars.html" class="nav-link active">Consumbles</a>
            </li>
        </ul>
    </div>
</li>
{% endblock %} 

{% block header %}
<!-- Divider -->
<div class="vr bg-gray-700 mx-1 mx-md-2 mx-lg-3"></div>
                    
<!-- Link -->
<a href="mailto:support@dashly-theme.com" class="btn btn-link mx-1 mx-lg-2 fw-semibold d-none d-md-block">
    Help
</a>

<!-- Link -->
<a href="https://themes.getbootstrap.com/product/dashly-admin-dashboard-template/" target="_blank" class="btn btn-primary mx-1 mx-lg-2 px-4 px-lg-5">
    Purchase Now
</a>

<!-- Link -->
<a href="../index.html" class="btn btn-dark mx-1 mx-lg-2 px-4 px-lg-5">
    User Manual
</a>
{% endblock %} 


{% block body %}
<h1 class="h2">
    Assets
</h1>

<div class="card border-0 flex-fill w-100">

    <div class="card-header border-0 card-header-space-between">
        <!-- Title -->
        <h2 class="card-header-title h4 text-uppercase">
            Vehicle Fleet
        </h2>
        
        <!-- Dropdown -->
        <div class="dropdown">
            <a href="javascript: void(0);" class="dropdown-toggle no-arrow text-secondary" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" height="14" width="14"><g><circle cx="12" cy="3.25" r="3.25" style="fill: currentColor"/><circle cx="12" cy="12" r="3.25" style="fill: currentColor"/><circle cx="12" cy="20.75" r="3.25" style="fill: currentColor"/></g></svg>
            </a>
            <div class="dropdown-menu">
                <a href="javascript: void(0);" class="dropdown-item">
                    Export report
                </a>
                <a href="javascript: void(0);" class="dropdown-item">
                    Share
                </a>
                <a href="javascript: void(0);" class="dropdown-item">
                    Action
                </a>
            </div>
        </div>
    </div>
    
    <div class="card-body">
        {% if vehicle_list %}
        <div class="table-responsive">
            <table id="fleetTable" class="table align-middle table-sm table-edge table-nowrap mb-0">
                <thead class="thead-light">
                    <tr>
                        <th>VIN</th>
                        <th>Assembly date</th>
                        <th class="text-end">Entry into service</th>
                    </tr>
                </thead>
                <tbody>
                    {% for vehicle in vehicle_list %} 
                    <tr>
                        <td>
                            <a href="{% url 'assets:vehicle_detail' vehicle.id %}">{{ vehicle.vin }}</a>
                        </td>
                        <td class="text-muted">{{vehicle.assembly_date | date:"d.m.Y"}}</td>
                        <td class="text-end">{{vehicle.entry_into_service | date:"d.m.Y"}}</td>
                    </tr>
                    {% endfor %} 
                </tbody>
            </table>
        </div>
        {% else %}
            <p>No vehicle in database.</p>
        {% endif %}  
    </div>

    <div class="card-footer text-muted">
        Total: {{ total }}
    </div>


</div>

{% endblock %} 

templates/assets/vehicle_list.html
{% extends 'base.html' %}
{% load static %}

<!-- Page specific css -->
{% block css %}
{% endblock %}


{% block navar %}

<li class="nav-item">
    <span class="h6 text-secondary ps-4 ps-lg-6 mb-3 d-block text-uppercase">Getting started</span>
</li>

<!--Maintenance-->
<li class="nav-item dropdown">
    <a class="nav-link" href="#maintenance" data-bs-toggle="collapse" role="button" aria-expanded="false"
        aria-controls="customization">
        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-tools nav-link-icon" viewBox="0 0 16 16">
            <path d="M1 0 0 1l2.2 3.081a1 1 0 0 0 .815.419h.07a1 1 0 0 1 .708.293l2.675 2.675-2.617 2.654A3.003 3.003 0 0 0 0 13a3 3 0 1 0 5.878-.851l2.654-2.617.968.968-.305.914a1 1 0 0 0 .242 1.023l3.27 3.27a.997.997 0 0 0 1.414 0l1.586-1.586a.997.997 0 0 0 0-1.414l-3.27-3.27a1 1 0 0 0-1.023-.242L10.5 9.5l-.96-.96 2.68-2.643A3.005 3.005 0 0 0 16 3c0-.269-.035-.53-.102-.777l-2.14 2.141L12 4l-.364-1.757L13.777.102a3 3 0 0 0-3.675 3.68L7.462 6.46 4.793 3.793a1 1 0 0 1-.293-.707v-.071a1 1 0 0 0-.419-.814L1 0Zm9.646 10.646a.5.5 0 0 1 .708 0l2.914 2.915a.5.5 0 0 1-.707.707l-2.915-2.914a.5.5 0 0 1 0-.708ZM3 11l.471.242.529.026.287.445.445.287.026.529L5 13l-.242.471-.026.529-.445.287-.287.445-.529.026L3 15l-.471-.242L2 14.732l-.287-.445L1.268 14l-.026-.529L1 13l.242-.471.026-.529.445-.287.287-.445.529-.026L3 11Z"/>
          </svg>
        <span>Maintenance</span>
    </a>
    <div class="collapse" id="maintenance">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a href="/" class="nav-link active">Work orders</a>
            </li>
            <li class="nav-item">
                <a href="../docs/sass.html" class="nav-link">Scheduled Maintenance</a>
            </li>
            <li class="nav-item">
                <a href="../docs/javascript.html" class="nav-link">Task Groups</a>
            </li>
            <li class="nav-item">
                <a href="../docs/handlebars.html" class="nav-link">Projects</a>
            </li>
        </ul>
    </div>
</li>
<!--/Maintenance-->
<!--Assets-->
<li class="nav-item dropdown">
    <a class="nav-link" href="#assets" data-bs-toggle="collapse" role="button" aria-expanded="false"
        aria-controls="customization">
        <svg viewBox="0 0 24 24" class="nav-link-icon" height="18" width="18" xmlns="http://www.w3.org/2000/svg">
            <path d="M3.753,13.944v8.25h6v-6a1.5,1.5,0,0,1,1.5-1.5h1.5a1.5,1.5,0,0,1,1.5,1.5v6h6v-8.25" fill="none"
                stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></path>
            <path d="M.753,12.444,10.942,2.255a1.5,1.5,0,0,1,2.122,0L23.253,12.444" fill="none" stroke="currentColor"
                stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></path>
        </svg>
        <span>Assets</span>
    </a>
    <div class="collapse show" id="assets">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a href="{% url 'assets:vehicle_list' %}" class="nav-link active">Fleet</a>
            </li>
            <li class="nav-item">
                <a href="../docs/sass.html" class="nav-link">Equipment</a>
            </li>
            <li class="nav-item">
                <a href="../docs/javascript.html" class="nav-link">Tools</a>
            </li>
            <li class="nav-item">
                <a href="../docs/handlebars.html" class="nav-link">Consumbles</a>
            </li>
        </ul>
    </div>
</li>
<!--/Assets-->

{% endblock %} 

{% block header %}
<!-- Divider -->
<div class="vr bg-gray-700 mx-1 mx-md-2 mx-lg-3"></div>
                    
<!-- Link -->
<a href="mailto:support@dashly-theme.com" class="btn btn-link mx-1 mx-lg-2 fw-semibold d-none d-md-block">
    Help
</a>

<!-- Link -->
<a href="https://themes.getbootstrap.com/product/dashly-admin-dashboard-template/" target="_blank" class="btn btn-primary mx-1 mx-lg-2 px-4 px-lg-5">
    Purchase Now
</a>

<!-- Link -->
<a href="../index.html" class="btn btn-dark mx-1 mx-lg-2 px-4 px-lg-5">
    User Manual
</a>
{% endblock %} 


{% block body %}
<h1 class="h2">
    Assets
</h1>



<div class="row">
    {% for vehicle in vehicle_list %} 
    
    <div class="col-xxl-3 d-flex">
        <!-- Card -->
        <div class="card border-0 flex-fill w-100">
            <div class="card-header border-0 card-header-space-between">
                <!-- Title -->
                <h2 class="card-header-title h4 text-uppercase">
                    <a href="{% url 'assets:vehicle_detail' vehicle.id %}">{{ vehicle.vin }}</a>
                </h2>
                
                <!-- Dropdown -->
                <div class="dropdown">
                    <a href="javascript: void(0);" class="dropdown-toggle no-arrow text-secondary" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" height="14" width="14"><g><circle cx="12" cy="3.25" r="3.25" style="fill: currentColor"/><circle cx="12" cy="12" r="3.25" style="fill: currentColor"/><circle cx="12" cy="20.75" r="3.25" style="fill: currentColor"/></g></svg>
                    </a>
                    <div class="dropdown-menu">
                        <a href="javascript: void(0);" class="dropdown-item">
                            Export report
                        </a>
                        <a href="javascript: void(0);" class="dropdown-item">
                            Share
                        </a>
                        <a href="javascript: void(0);" class="dropdown-item">
                            Action
                        </a>
                    </div>
                </div>
            </div>
            {% if vehicle.image %}
                <img src="{{vehicle.image.url}}" style="width:100%">
            {% endif%} 

            <!-- Table -->
            <div class="table-responsive">
                <table id="projectsTable" class="table align-middle table-edge table-nowrap mb-0">
                    <thead class="thead-light">
                        <tr>
                            <th>Assembly date</th>
                            <th class="text-end">Entry into service</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="text-muted">{{ vehicle.assembly_date | date:"d.m.Y" }}</td>
                            <td class="text-muted text-end">{{ vehicle.entry_into_service | date:"d.m.Y" }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            
        
        </div>
    </div>
    {% endfor %} 
</div>

{% endblock %} 

{% block js %}
{% endblock %}