blog/urls.py
from django.urls import path

from.models import Post

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('post/<str:slug>/', views.PostsByCategory.as_view(), name='post'),
    path('category/<str:slug>/', views.get_category, name='category'),
]

web_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('assets/', include('assets.urls')),
    path('fasteners/', include('fasteners.urls')),
    path('blog/', include('blog.urls')),
    #ckeditor
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, verbose_name='Url', unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:category', kwargs={'slug':self.slug})

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ['title']


class Tag(models.Model):
    title = models.CharField(max_length=64)
    slug = models.SlugField(max_length=64, verbose_name='Url', unique=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']

class Post(models.Model):
    title = models.CharField(max_length=128)
    slug = models.SlugField(max_length=128, verbose_name='Url', unique=True)
    content = models.TextField(blank=True)
    created_at = models.DateField(auto_now_add=True, verbose_name='Published')
    image = models.ImageField(upload_to='blog/images/', null=True, blank=True)
    views = models.IntegerField(default=0, verbose_name="Viewed")
    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='posts')
    tags = models.ManyToManyField(Tag, blank=True, related_name="posts")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post', kwargs={'slug':self.slug})

    class Meta:
        ordering = ['-created_at']

blog/views.py
from django.shortcuts import render

from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator

from.models import Category, Tag, Post

class Home(ListView):
    model = Post
    template_name ='blog/index.html'
    context_object_name = 'posts'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Blog for Something'
        return context

def get_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    return render (request, 'blog/post.html', {'post': post})


def get_category(request, slug):
    category = get_object_or_404(Category, slug=slug)
    return render (request, 'blog/category.html', {'category': category})


class PostsByCategory(ListView):
    template_name ='blog/index.html'
    context_object_name = 'posts'
    paginate_by = 1

    def get_queryset(self):
        return Post.objects.filter(category__slug = self.kwargs('slug'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Category.objects.get(slug = self.kwargs('slug'))
        return context

templates/blog/includes/_footer.html
{% load menu %}
<footer class="site-footer bg-dark">

    <div class="container">

            {% show_menu_footer %}  

        <div class="copy">
            &copy; Silo 2022<br />
            All rights reserved
        </div>
    </div>
    
</footer>

templates/blog/includes/_header.html
{% load menu %}
<header class="menu">
    <nav class="navbar navbar-expand-md navbar-light bg-white absolute-top">

        <div class="container">

            <button class="navbar-toggler order-2 order-md-1" type="button" data-bs-toggle="collapse"
                data-bs-target=".navbar-collapse" aria-controls="navbar-left navbar-right" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <a class="navbar-brand mx-auto order-1 order-md-1" href="{% url 'blog:home' %}">matus</a>

            

            <div class="collapse navbar-collapse order-2 order-md-2" id="navbar-right">
                
                {% show_menu_header %}

                <form class="form-inline" role="search">
                    <input class="search js-search form-control form-control-rounded me-sm-2" type="text"
                        title="Enter search query here.." placeholder="Search.." aria-label="Search">
                </form>
            </div> 
        </div>
    </nav>
</header>

templates/blog/includes/_site-instagram.html
{% load static %}
<div class="site-instagram">
    <div class="action">
      <a class="btn btn-light" href="#">
        Follow us @ Instagram
      </a>
    </div>
    <div class="row g-0">
      <div class="col-sm-6">
        <div class="row g-0">
          <div class="col-3">
            <a class="photo" href="#">
              <img class="img-fluid" src="{% static 'blog/images/1.jpg' %}" alt="" />
            </a>
          </div>
          <div class="col-3">
            <a class="photo" href="#">
              <img class="img-fluid" src="{% static 'blog/images/2.jpg' %}" alt="" />
            </a>
          </div>
          <div class="col-3">
            <a class="photo" href="#">
              <img class="img-fluid" src="{% static 'blog/images/3.jpg' %}" alt="" />
            </a>
          </div>
          <div class="col-3">
            <a class="photo" href="#">
              <img class="img-fluid" src="{% static 'blog/images/4.jpg' %}" alt="" />
            </a>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="row g-0">
          <div class="col-3">
            <a class="photo" href="#">
              <img class="img-fluid" src="{% static 'blog/images/5.jpg' %}" alt="" />
            </a>
          </div>
          <div class="col-3">
            <a class="photo" href="#">
              <img class="img-fluid" src="{% static 'blog/images/6.jpg' %}" alt="" />
            </a>
          </div>
          <div class="col-3">
            <a class="photo" href="#">
              <img class="img-fluid" src="{% static 'blog/images/7.jpg' %}" alt="" />
            </a>
          </div>
          <div class="col-3">
            <a class="photo" href="#">
              <img class="img-fluid" src="{% static 'blog/images/8.jpg' %}" alt="" />
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>

templates/blog/includes/_site-newsletter.html
<div class="site-newsletter">
    <div class="container">
        <div class="text-center">
            <h3 class="h4 mb-2">Subscribe to our newsletter</h3>
            <p class="text-muted">Join our monthly newsletter and never miss out on new stories and promotions.</p>

            <div class="row">
                <div class="col-xs-12 col-sm-9 col-md-7 col-lg-5 ms-auto me-auto">
                    <div class="input-group mb-3 mt-3">
                        <input type="text" class="form-control" placeholder="Email address" aria-label="Email address">
                        <span class="input-group-btn">
                            <button class="btn btn-secondary" type="button">Subscribe</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/blog/includes/header.html
<header>
    <nav class="navbar navbar-expand-md navbar-light bg-white absolute-top">
        <div class="container">

            <button class="navbar-toggler order-2 order-md-1" type="button" data-bs-toggle="collapse"
                data-bs-target=".navbar-collapse" aria-controls="navbar-left navbar-right" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse order-3 order-md-2" id="navbar-left">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="page-about.html">Driver Manual</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="page-about.html">Multi</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="page-about.html">SDP3</a>
                    </li>
                </ul>
            </div>

            <a class="navbar-brand mx-auto order-1 order-md-3" href="index.html">matus</a>

            <div class="collapse navbar-collapse order-4 order-md-4" id="navbar-right">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="page-about.html">XCOM</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="page-contact.html">ab WEB</a>
                    </li>
                </ul>
                <form class="form-inline" role="search">
                    <input class="search js-search form-control form-control-rounded me-sm-2" type="text"
                        title="Enter search query here.." placeholder="Search.." aria-label="Search">
                </form>
            </div>
        </div>
    </nav>
</header>